// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwanlRQh9e3Hr4coVJwwO1NTZGk03fXI',
    appId: '1:210800028736:web:6a453f5de878da48d8c3a5',
    messagingSenderId: '210800028736',
    projectId: 'abot-agri',
    authDomain: 'abot-agri.firebaseapp.com',
    storageBucket: 'abot-agri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsjelkn42lq56MjU77QSzvIGor5zhn-Zk',
    appId: '1:210800028736:android:087d78e00662bde8d8c3a5',
    messagingSenderId: '210800028736',
    projectId: 'abot-agri',
    storageBucket: 'abot-agri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWyhIfhxuAhliYfE0AKIB_wxVcBA_aqZI',
    appId: '1:210800028736:ios:2283bbd623dbdc92d8c3a5',
    messagingSenderId: '210800028736',
    projectId: 'abot-agri',
    storageBucket: 'abot-agri.firebasestorage.app',
    androidClientId: '210800028736-0s71gi307l2sf2h3vcd9kdiok29aufr3.apps.googleusercontent.com',
    iosClientId: '210800028736-n7080d83defd7otbhni4p8kc1drt8k0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWyhIfhxuAhliYfE0AKIB_wxVcBA_aqZI',
    appId: '1:210800028736:ios:2283bbd623dbdc92d8c3a5',
    messagingSenderId: '210800028736',
    projectId: 'abot-agri',
    storageBucket: 'abot-agri.firebasestorage.app',
    androidClientId: '210800028736-0s71gi307l2sf2h3vcd9kdiok29aufr3.apps.googleusercontent.com',
    iosClientId: '210800028736-n7080d83defd7otbhni4p8kc1drt8k0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuwanlRQh9e3Hr4coVJwwO1NTZGk03fXI',
    appId: '1:210800028736:web:e55e3c5189300139d8c3a5',
    messagingSenderId: '210800028736',
    projectId: 'abot-agri',
    authDomain: 'abot-agri.firebaseapp.com',
    storageBucket: 'abot-agri.firebasestorage.app',
  );
}
